### ISSUE TITLE
429 Error after calling Infura endpoint

### ISSUE THREAD

**Issue by germartinez** [MolochVentures/moloch-monorepo#100]
Hello,

When I'm trying to log in with the Gnosis Safe Authenticator here `https://molochdao.com/login` I get this screen sometimes and it never ends loading.
![molochdao1](https://user-images.githubusercontent.com/6764315/64253741-32d06f00-cf1e-11e9-9864-dc78e6256344.PNG)

After refreshing the page everything seems to be fine.
![molochdao2](https://user-images.githubusercontent.com/6764315/64253744-34019c00-cf1e-11e9-8944-ec67d229ef5e.PNG)

However, if now I use the log out and log in buttons, the console returns this error https://httpstatuses.com/429 after calling the Infura endpoint.
![molochdao3](https://user-images.githubusercontent.com/6764315/64253746-3532c900-cf1e-11e9-84fe-75ddedadb419.PNG)

This endpoint should be used `mainnet.infura.io/v3/<token>` instead of this one `mainnet.infura.io/<token>` (https://blog.infura.io/introducing-the-infura-dashboard-8969b7ab94e7)

If you need anything, I work on the Gnosis Safe Authenticator ;)

Thank you!

**Comment by rhlsthrm** [comment]
Hi @germartinez, I switched the Infura endpoint to point at the v3 token. I'm not sure why it was on the old style endpoint, thanks for reporting. As for the Gnosis safe issues, I'd love your help on digging into it, I haven't actually messed with it much since I don't have one with mainnet ETH.
