### ISSUE TITLE
Truffle test can not connect to the ganach client 

### ISSUE THREAD

**Issue by Npizza** [MolochVentures/moloch-monorepo#103]
I run the` truffle test test/single.js` to get the `moloch.address` but the truffle can not connect to the ganache client. 

I looked at the truffle-config.js and it is like that:

```
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 8545,
      gas: 4700000,
      network_id: '*' // Match any network id
    },
```

We have to change host to 0.0.0.0 to connect truffle correctly.

**Comment by RyRy79261** [comment]
@Npizza What OS are you running?

It could have something to do with how your localhost is getting set up in this case.

**Comment by Npizza** [comment]
I found the solution on the changing the host to 0.0.0.0 ;)
