### ISSUE TITLE
Bad UX when using the "Approve wETH" functionality

### ISSUE THREAD

**Issue by jbrukh** [MolochVentures/moloch-monorepo#23]
There is no sign the transaction is sent, validated, or rejected.

**Comment by rhlsthrm** [comment]
Planning to implement a full transaction monitoring UX for all the onchain transactions, thanks for opening.

**Comment by rhlsthrm** [comment]
Actually this is a duplicate of #13, I will close this in favor of that, which addresses all transactions, not just "approve wETH".
