### ISSUE TITLE
Improve responsiveness, UX by updating proposal page to a single column format.

### ISSUE THREAD

**Issue by as-dr** [MolochVentures/moloch-monorepo#26]
Currently, the [proposals](https://molochdao.com/proposals) page is broken into two columns, with linked categories in a smaller left-hand column. This is ok on desktop but requires a responsive design that changes at smaller screen sizes.

A simpler approach, which works on both desktop and mobile and establishes and explicit information hierarchy would be to place the proposal tabs above the proposals, in a new single column layout:

<img width="1351" alt="Screen Shot 2019-04-14 at 9 36 04 PM" src="https://user-images.githubusercontent.com/6787950/56101866-b9989700-5efe-11e9-828c-78bf732a9dc7.png">

At smaller viewports, you can simply set the tabs to `overflow: scroll`, allowing mobile users to scroll across the tabs, like so:

<img width="338" alt="Screen Shot 2019-04-14 at 9 43 03 PM" src="https://user-images.githubusercontent.com/6787950/56101881-cae1a380-5efe-11e9-9506-15ab8b36b15d.png">

([Here are some approaches to hiding the scrollbar](https://stackoverflow.com/questions/16670931/hide-scroll-bar-but-while-still-being-able-to-scroll))

This approach would:

1. Reduce site maintenance & build (through less need for media queries & viewport specific styles)
2. Maintain consistency across multiple viewports
3. Help establish an information architecture for the whole site.
4. Be implicitly easier to navigate, parse, and understand (thanks in part to #3)

**Comment by rhlsthrm** [comment]
Fixed and deployed.
