### ISSUE TITLE
ui label label for donate modal undefined

### ISSUE THREAD

**Issue by dangerousfood** [MolochVentures/moloch-monorepo#67]
<img width="1414" alt="Screen Shot 2019-08-13 at 9 46 08 AM" src="https://user-images.githubusercontent.com/4099038/62951696-02c6fd80-bdb0-11e9-992b-6c063f3be892.png">
<img width="1414" alt="Screen Shot 2019-08-13 at 9 51 08 AM" src="https://user-images.githubusercontent.com/4099038/62951702-065a8480-bdb0-11e9-9d43-08e7489b78c4.png">

**Comment by dangerousfood** [comment]
Seems to resolve itself I use the web3 login. I imagine that is how it should work but maybe we give an error modal if they haven't logged in yet.

<img width="1414" alt="Screen Shot 2019-08-13 at 9 59 13 AM" src="https://user-images.githubusercontent.com/4099038/62952318-0909a980-bdb1-11e9-900c-563e3615096e.png">

**Comment by rhlsthrm** [comment]
Ah, you're right, this will definitely be an issue, thanks for reporting.

**Comment by dangerousfood** [comment]
Maybe diable the button and gray it out and when they moluseover the button it tells them it is available after they log in
