### ISSUE TITLE
Problem creating subgraph

### ISSUE THREAD

**Issue by Npizza** [MolochVentures/moloch-monorepo#90]
Hi I am trying to replicate the moloch following the instructions at the Readme.
When I am at the **create subgraph** section I run the command 
`graph create moloch --node http://127.0.0.1:8020`
But I get this error:
```

Could not get access token from libsecret (usually gnome-keyring or ksecretservice): Cannot autolaunch D-Bus without X11 $DISPLAY
Continuing without an access token

✖ HTTP error creating the subgraph: ECONNRESET
```

Also I get a  WARN:
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
`
When I am trying to do  `npm install` at path `moloch-monorepo/packages/subgraph
`
Is that something that I should fix or it is just something minor?

I am working on Ubuntu droplet from digital ocean.
What could I try to fix this?

**Comment by rhlsthrm** [comment]
The npm warning is minor and skippable, however your error is strange. I haven't tried to spin up a local subgraph in a while, I always point at the deployed subgraph. I'll update the readme instructions to better reflect this, and also I will try the subgraph on my own.

**Comment by Npizza** [comment]
I asked at the Discord of Graph project and say to me that probably the graph node has not started correctly. I am still looking at it. I will update the issue when I found the solution.
