### ISSUE TITLE
npm install -g @graphprotocol/graph-cli Throws  error

### ISSUE THREAD

**Issue by Npizza** [MolochVentures/moloch-monorepo#93]
On ubuntu I am trying to install **graph-cli**  with the command 
`npm install -g @graphprotocol/graph-cli`
But it is failing:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/@graphprotocol/graph-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.9.10 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.9.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-01T12_51_54_404Z-debug.log

```

I think that I found a work around this problem with using:

`yarn global add @graphprotocol/graph-cli`

I followed the instructions from here:
https://github.com/graphprotocol/graph-cli

**Comment by rhlsthrm** [comment]
What is the difference between the work around command and the original command? Both are doing `npm install -g @graphprotocol/graph-cli`.

**Comment by Npizza** [comment]
You are right! I copy past the wrong command. My mistake, I edit it with the correct one
